In [1]:
import numpy as np
import pandas as pd
import json

In [11]:
import json

def remove_duplicate_answers_correctly(data):
    """
    Removes duplicate answers from the 'generated_answers' list for each 
    question and preserves the corresponding 'ground_truth_labels'.

    Args:
        data: The JSON data loaded as a Python dictionary.

    Returns:
        The modified JSON data with duplicate answers and their corresponding
        labels correctly handled.
    """
    for question, details in data.items():
        if "generated_answers" not in details:
            continue

        unique_answers = []
        new_labels = []
        seen_answers = set()
        
        original_answers = details["generated_answers"]
        original_labels = details.get("ground_truth_labels", [])

        # Iterate through answers with their original index
        for i, answer in enumerate(original_answers):
            if answer not in seen_answers:
                seen_answers.add(answer)
                unique_answers.append(answer)
                
                # Use the original index 'i' to append the correct label
                if i < len(original_labels):
                    new_labels.append(original_labels[i])

        details["generated_answers"] = unique_answers
        details["ground_truth_labels"] = new_labels
            
    return data

# Load the JSON data from the file
with open('negated_popqa.json', 'r') as f:
    halueval_data = json.load(f)

# Remove duplicate answers using the corrected function
modified_data = remove_duplicate_answers_correctly(halueval_data)

# Print the modified data to verify
# print(json.dumps(modified_data, indent=2))

with open('negated_popqa.json', 'w') as f:
    json.dump(modified_data, f, indent=2)

In [3]:
import pandas as pd

df = pd.read_csv('C:/Users/arshm/Documents/Code/Viveka/linear_experiment_2_NN_Probing/datasets/eval_data/halueval.csv')

In [4]:
df.head()

,knowledge,raw_question,correct_answer,hallucinated_answer
0,Arthur's Magazine (1844–1846) was an American ...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,First for Women was started first.
1,The Oberoi family is an Indian family that is ...,The Oberoi family is part of a hotel company t...,Delhi,The Oberoi family's hotel company is based in ...
2,"Allison Beth ""Allie"" Goertz (born March 2, 199...",Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,"Allie Goertz wrote a song about Milhouse, a po..."
3,"Margaret ""Peggy"" Seeger (born June 17, 1935) i...",What nationality was James Henry Miller's wife?,American,James Henry Miller's wife was British.
4,It is a hygroscopic solid that is highly solu...,Cadmium Chloride is slightly soluble in this c...,alcohol,water with a hint of alcohol

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   knowledge            2000 non-null   object
 1   raw_question         2000 non-null   object
 2   correct_answer       2000 non-null   object
 3   hallucinated_answer  2000 non-null   object
dtypes: object(4)
memory usage: 62.6+ KB

In [ ]:
df.duplicated().any()

False

In [3]:
df_unique = pd.read_json("C:/Users/arshm/Downloads/google_gemma-2-2b-it_generations.json")

# df_unique = pd.read_json(r"./args.generations_dir/arg.generations_file")
#df_unique
row = df_unique.loc["generated_answers"]
len_list = row.apply(len).tolist()
avg = sum(len_list)/len(len_list)
print(f"number of questions : {len(len_list)}\navg no. of unique ans per qn: {avg}")

number of questions : 2000
avg no. of unique ans per qn: 32.0

In [13]:
file_path = 'C:/Users/arshm/Downloads/Phone Link/meta-llama-Llama-3.2-3B-Instruct 0-3.2k.json'
df_unique = pd.read_json(file_path)
row = df_unique.loc["generated_answers"]
len_list = row.apply(len).tolist()
avg = sum(len_list) / len(len_list)
print(f"number of questions : {len(len_list)}")
print(f"avg no. of unique ans per qn: {avg}")

number of questions : 3200
avg no. of unique ans per qn: 32.0

In [2]:
# file_path = 'C:/Users/arshm/Downloads/Phone Link/meta-llama-Llama-3.2-3B-Instruct 0-3.2k.json'
df1 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 0-3.2k.json',orient='columns')
df1.head()

,What city is Kowloon a part of?,The Austrian metalworking company Kraftfahrzeuge Trunkenpolz Mattighofen founded in 1934 is nowadays better known as a manufacturer of what?,Who made the album Captain Fantastic and the Brown Dirt Cowboy,In which country was designer Oscar de la Renta born?,Which artist did Chariton Heston play in the 1965 film ‘the Agony and the Ecstasy?,What was the primary tank used by the United States in World War 2?,In which American state was Edward Snowden working as a contractor to the National Security Agency when he decided to leak secrets?,"Freckles, brownish yellow spots usually found mostly on the face, neck and hands are also known as . ?","Which word can go before Star, Axe and Cat to make three other words?",What Jewish-born Prime Minister led the United Kingdom?,...,"Resembling a long-tailed rabbit, which South American rodent is bred in captivity for its soft grey fur?",Which actor and TV personality has been a judge on many musical talent shows and hosts 'Tonight's the Night'?,"""A label on a fabric saying that it is """"colourfast"""" means what?""","Babcock, Elberta and Rubidoux are all varieties of which fruit?","""Which Roman emperor's last words were reputedly """"What an artist the world is losing in me""""?""",Whom did St.Paul describe as 'his beloved physician'?,Which normal human spasm has the medical term ptarmus?,What name did Pol Pot give to the ideology that he forced on the people of Democratic Kampuchea?,Cricket - which Yorkshireman scored a then Test record 364 runs against Australia at the Oval in 1938 ?,The TV series 'Angel' is-a spin off from which other
prompt,<start_of_turn>user\nQ: What city is Kowloon a...,<start_of_turn>user\nQ: The Austrian metalwork...,<start_of_turn>user\nQ: Who made the album Cap...,<start_of_turn>user\nQ: In which country was d...,<start_of_turn>user\nQ: Which artist did Chari...,<start_of_turn>user\nQ: What was the primary t...,<start_of_turn>user\nQ: In which American stat...,"<start_of_turn>user\nQ: Freckles, brownish yel...",<start_of_turn>user\nQ: Which word can go befo...,<start_of_turn>user\nQ: What Jewish-born Prime...,...,<start_of_turn>user\nQ: Resembling a long-tail...,<start_of_turn>user\nQ: Which actor and TV per...,"<start_of_turn>user\nQ: ""A label on a fabric s...","<start_of_turn>user\nQ: Babcock, Elberta and R...","<start_of_turn>user\nQ: ""Which Roman emperor's...",<start_of_turn>user\nQ: Whom did St.Paul descr...,<start_of_turn>user\nQ: Which normal human spa...,<start_of_turn>user\nQ: What name did Pol Pot ...,<start_of_turn>user\nQ: Cricket - which Yorksh...,<start_of_turn>user\nQ: The TV series 'Angel' ...
generated_answers,[Kowloon is a part of Hong Kong. <end_of_turn>...,[The Austrian metalworking company Kraftfahrze...,[The album *Captain Fantastic and the Brown Di...,[Oscar de la Renta was born in Puerto Rico.<en...,[Chariton Heston did not play a role in the 19...,[1. The primary tank used by the United States...,[start of turn Edward Snowden was working as a...,"[Freckles, brownish yellow spots usually found...","[The word that can go before ""Star,"" ""Axe,"" an...",[end_of_turn\n<start_of_turn>user\nQ: What Jew...,...,[The South American rodent resembling a long-t...,[start_of_turn\nThe actor and TV personality y...,"[A label on a fabric saying that it is ""colour...","[start of turn\nBabcock, Elberta, and Rubidoux...",[The Roman emperor whose last words were reput...,"[1. Paul is referring to the Apostle Paul, and...","[end_of_turn\n\nThe medical term ""ptarmus"" is ...","[Pol Pot referred to his ideology as ""Khmer Ro...",[The Yorkshireman who scored a then Test recor...,"[turner's ""Buffy the Vampire Slayer""<end_of_tu..."
ground_truth_labels,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",...,"[0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, ...","[0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, ...","[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [3]:
df2 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 3.2K-6.4K.json',orient='columns')
df2.head()

,"The Fynbos, an area of grassland and thicket, lies in which African country?","""Who composed """"The Karelia Suite""""?""","Over which country did RAF Bomber Command make food drops, codenamed ‘Operation Manna’, in April 1945?",What does the musical instruction 'Subito' mean?,In which Charles Dickens Novel does Esther Summerson appear?,Who wrote the poem The Rape of the Lock?,The WMO is an agency of the UN dealing with what?,"What do FDJ, Rabobank, RadioShack, Astana, Garmin-Cervlo, Saur-Sojasun, Saxo Bank-SunGard, HTC-Highroad, Sky, Cofidis, Katusha, Europcar, Omega Pharma-Lotto, Leopard Trek, and Movistar have in common?","""Who wrote most of the operetta, """"The Tales of Hoffman"""", which although unfinished at his death, was completed by Ernest Guiraud?""","Why was Los Angeles selected as the host of the 1984 Summer Olympic Games by the IOC session at Athens, Greece, without a vote?",...,"""What was the first name of the character """"Rigsby"""" in the TV comedy """"Rising Damp""""?""","Leon Trotsky, who had been Russia's foreign secretary from 1918 under Lenin, was exiled to Siberia in 1927 after Lenin's death. How did he die?",Which was the second James Bond movie?,The 500 peso note issued by the Bank of Mexico in 2010 contains the image of the artist Diego Rivera on the obverse side. Whose image is on the reverse side?,"According to the gospel of Luke, Zachariah and his barren wife Elizabeth were the parents of which great Biblical character?",Which Mediterranean island is divided politically by the Attila Line?,"At the 1896 Athens Summer Olympic Games, the winners were given a silver medal and a branch from which type of tree?",What UK government-funded company traditionally employing disabled people in manufacturing was founded in 1945 to provide work for injured soldiers?,What is Magic Johnson's real first name?,Who played both the Kray twins in the film Legend?
prompt,"<start_of_turn>user\nQ: The Fynbos, an area of...","<start_of_turn>user\nQ: ""Who composed """"The Ka...",<start_of_turn>user\nQ: Over which country did...,<start_of_turn>user\nQ: What does the musical ...,<start_of_turn>user\nQ: In which Charles Dicke...,<start_of_turn>user\nQ: Who wrote the poem The...,<start_of_turn>user\nQ: The WMO is an agency o...,"<start_of_turn>user\nQ: What do FDJ, Rabobank,...","<start_of_turn>user\nQ: ""Who wrote most of the...",<start_of_turn>user\nQ: Why was Los Angeles se...,...,"<start_of_turn>user\nQ: ""What was the first na...","<start_of_turn>user\nQ: Leon Trotsky, who had ...",<start_of_turn>user\nQ: Which was the second J...,<start_of_turn>user\nQ: The 500 peso note issu...,<start_of_turn>user\nQ: According to the gospe...,<start_of_turn>user\nQ: Which Mediterranean is...,<start_of_turn>user\nQ: At the 1896 Athens Sum...,<start_of_turn>user\nQ: What UK government-fun...,<start_of_turn>user\nQ: What is Magic Johnson'...,<start_of_turn>user\nQ: Who played both the Kr...
generated_answers,[The Fynbos is not located in Africa. It is a ...,[turner<br>the karelia suite was composed by t...,"[RAF Bomber Command made food drops, codenamed...","[Subito means ""suddenly"" in Italian. In musica...",[Esther Summerson appears in Charles Dickens's...,"[The poem ""The Rape of the Lock"" was written b...",[climate and weather</end_of_turn> \n<start_of...,[These organizations are all professional cycl...,[The operetta *The Tales of Hoffman* was prima...,[Los Angeles was selected as the host of the 1...,...,"[1. The character ""Rigsby"" does not appear in ...",[Leon Trotsky was assassinated in 1940 in Mexi...,[007: The Spy Who Loved Me was the second Jame...,[The reverse side of the 500 peso note issued ...,"[According to the Gospel of Luke, Zachariah an...",[Q: Which Mediterranean island is divided poli...,"[At the 1896 Athens Summer Olympic Games, the ...","[1945, the UK government founded the National ...",[start of turn\nMagic Johnson's real first nam...,[The Kray twins were portrayed in the film *Le...
ground_truth_labels,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, ..."

In [4]:

df3 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 6.4-9.6k.json',orient='columns')
df4 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 9.6k-12.8k.json',orient='columns')
df5 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 12.8k-16k.json',orient='columns')
df8 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/qwen-4b-instruct 19.2-20k.json',orient='columns')

In [5]:

df6 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/Qwen_Qwen3-4B-Instruct-16-17.6k.json',orient='columns')
df6.head()

,"""Name the actress, who played the part of Nurse Chappel in the original TV series, """"Star Trek"""", and married the creator Gene Roddenberry in 1969.""",The Tarantella is a form of folk music and a ballroom dance originating from which country?,"""With which sport do you associate """"Flushing Meadow""""?""","The lands of Castile, which came to prominence in Europe in the 13th century, make up much of which modern country?","Meaning 'place of sunset' or 'western' in Arabic, which word is generally applied to the geographic area of Morocco, Algeria and Tunisia together?","Which British city was once said to be famous for Jam, Jute and Journalism?",What is the longest exposed mountain range in the world?,WE FATTEN HIGH MOTHERS (Shakespeare),Which part does Matt Damon play in the film 'Invictus'?,Who played the Vicar of Dibley on TV?,...,A 'Winter Nelis' is a variety of which fruit?,'Lager' beer is named from German meaning?,Cass Gilbert was the major developer of what type of building?,"""The song """"We have all the time in the World"""" by Louis Armstrong provided the theme for which James Bond film?""",Who would wear a 'Yarmulke'?,Who was King of England in the year 1400?,"According to the proverb, the road to hell is what?","According to Greek legend, Leander was visited nightly by whom, who swam across the Hellespont?","In mathematics, which letter is used for the constant which is approximately 2.7182818?","""Which twentieth century US President once said, """"They say hard work never killed anyone, but why take the chance""""?"""
prompt,"<start_of_turn>user\nQ: ""Name the actress, who...",<start_of_turn>user\nQ: The Tarantella is a fo...,"<start_of_turn>user\nQ: ""With which sport do y...","<start_of_turn>user\nQ: The lands of Castile, ...",<start_of_turn>user\nQ: Meaning 'place of suns...,<start_of_turn>user\nQ: Which British city was...,<start_of_turn>user\nQ: What is the longest ex...,<start_of_turn>user\nQ: WE FATTEN HIGH MOTHERS...,<start_of_turn>user\nQ: Which part does Matt D...,<start_of_turn>user\nQ: Who played the Vicar o...,...,<start_of_turn>user\nQ: A 'Winter Nelis' is a ...,<start_of_turn>user\nQ: 'Lager' beer is named ...,<start_of_turn>user\nQ: Cass Gilbert was the m...,"<start_of_turn>user\nQ: ""The song """"We have al...",<start_of_turn>user\nQ: Who would wear a 'Yarm...,<start_of_turn>user\nQ: Who was King of Englan...,<start_of_turn>user\nQ: According to the prove...,<start_of_turn>user\nQ: According to Greek leg...,"<start_of_turn>user\nQ: In mathematics, which ...","<start_of_turn>user\nQ: ""Which twentieth centu..."
generated_answers,[The actress who played the part of Nurse Chap...,[The Tarantella is a form of folk music and a ...,"[""Flushing Meadow"" is most commonly associated...",[Spain\n</end_of_turn>Human: What is the signi...,"[The word you're referring to is ""al-ma'qar"" —...",[The British city once said to be famous for J...,[The longest exposed mountain range in the wor...,"[""We fatten high mothers"" is not a line from W...","[In the film *Invictus*, Matt Damon plays the ...",[The Vicar of Dibley was played by Paul Whiteh...,...,[A 'Winter Nelis' is a variety of pear. \n</s...,"[""Lager"" beer is named from the German word *L...",[Cass Gilbert was the major developer of **pub...,"[The song ""We Have All the Time in the World"" ...",[A Yarmulke is traditionally worn by Jewish me...,"[In the year 1400, the King of England was Hen...","[According to the proverb, ""the road to hell i...","[According to Greek legend, Leander was visite...",[The letter used for the constant approximatel...,[The twentieth-century U.S. President who said...
ground_truth_labels,"[1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",...,"[1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [6]:

df7 = pd.read_json('C:/Users/arshm/Downloads/Phone Link/Qwen_Qwen3-4B-Instruct-17.6-19.2.json',orient='columns')

dfs = [df1,df2,df3,df4,df5,df6,df7,df8]

final_df = pd.concat(dfs, axis=1,ignore_index=True)

In [7]:
final_df.head()

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
prompt,<start_of_turn>user\nQ: What city is Kowloon a...,<start_of_turn>user\nQ: The Austrian metalwork...,<start_of_turn>user\nQ: Who made the album Cap...,<start_of_turn>user\nQ: In which country was d...,<start_of_turn>user\nQ: Which artist did Chari...,<start_of_turn>user\nQ: What was the primary t...,<start_of_turn>user\nQ: In which American stat...,"<start_of_turn>user\nQ: Freckles, brownish yel...",<start_of_turn>user\nQ: Which word can go befo...,<start_of_turn>user\nQ: What Jewish-born Prime...,...,<start_of_turn>user\nQ: Which British school h...,<start_of_turn>user\nQ: Which Hollywood Produc...,<start_of_turn>user\nQ: What TV artist who hel...,<start_of_turn>user\nQ: What sort of creature ...,<start_of_turn>user\nQ: What sort of professio...,<start_of_turn>user\nQ: What role is played by...,<start_of_turn>user\nQ: Which public service i...,<start_of_turn>user\nQ: Whish 1996 multi Oscar...,<start_of_turn>user\nQ: Crown Derby is what so...,<start_of_turn>user\nQ: Laura was the name of ...
generated_answers,[Kowloon is a part of Hong Kong. <end_of_turn>...,[The Austrian metalworking company Kraftfahrze...,[The album *Captain Fantastic and the Brown Di...,[Oscar de la Renta was born in Puerto Rico.<en...,[Chariton Heston did not play a role in the 19...,[1. The primary tank used by the United States...,[start of turn Edward Snowden was working as a...,"[Freckles, brownish yellow spots usually found...","[The word that can go before ""Star,"" ""Axe,"" an...",[end_of_turn\n<start_of_turn>user\nQ: What Jew...,...,[end_of_turn\nThe British school that holds it...,[The Hollywood producer who produced the films...,[The TV artist who helped popularise the Morph...,[Monarch is a type of butterfly. It is known f...,"[In most jurisdictions, only certain professio...",[1. Mark Gattis does not appear in the TV seri...,[24-hour public service located near Victoria ...,[The film *The Crying Game* is not a 1996 mult...,[end of turn\nCrown Derby is a type of porcela...,[Laura was the name of the First Lady of U.S. ...
ground_truth_labels,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",...,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, ...","[1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, ...","[1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, ..."

In [8]:
final_df.to_json(
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct_combined.json',
    orient='columns',      # ensures it's a list of dicts like original
    indent=2    # keeps Unicode characters intact
)

In [14]:
import pandas as pd

# List of your JSON file paths
files = [
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 0-3.2k.json',
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 3.2K-6.4K.json',
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 6.4-9.6k.json',
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 9.6k-12.8k.json',
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct 12.8k-16k.json',
    'C:/Users/arshm/Downloads/Phone Link/Qwen_Qwen3-4B-Instruct-16-17.6k.json',
    'C:/Users/arshm/Downloads/Phone Link/Qwen_Qwen3-4B-Instruct-17.6-19.2.json',
    'C:/Users/arshm/Downloads/Phone Link/qwen-4b-instruct 19.2-20k.json'
]

# Read each file with orient='columns'
dfs = [pd.read_json(file, orient='columns') for file in files]

# Combine them (handles column-based JSON structure)
final_df = pd.concat(dfs, ignore_index=True)

# Save in the SAME column-based JSON format
final_df.to_json(
    'C:/Users/arshm/Downloads/Phone Link/qwen3-4b-instruct_combined.json',
    orient='columns',
    indent=4,
    force_ascii=False
)

print("✅ Combined DataFrame shape:", final_df.shape)
print("✅ Saved to qwen3-4b-instruct_combined.json")

✅ Combined DataFrame shape: (24, 20000)
✅ Saved to qwen3-4b-instruct_combined.json