In [2]:
import numpy as np
import plotly.express as px
import pandas as pd

In [3]:
df = pd.read_csv('layer_ablation_results_triviaqa_10sv.csv')
df.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       52    100      0.52
1      1  blocks.1.hook_resid_post       44    100      0.44
2      2  blocks.2.hook_resid_post       52    100      0.52
3      3  blocks.3.hook_resid_post       45    100      0.45
4      4  blocks.4.hook_resid_post       47    100      0.47

In [12]:
fig = px.line(df, x="layer", y="accuracy", title="Accuracy v/s Layer with 100 generations (greedy) ablating 10 SVs")
fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")
fig.show()

In [5]:
df_1 = pd.read_csv('layer_ablation_results_2.csv')
df_1.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       43    100      0.43
1      1  blocks.1.hook_resid_post       28    100      0.28
2      2  blocks.2.hook_resid_post       37    100      0.37
3      3  blocks.3.hook_resid_post       47    100      0.47
4      4  blocks.4.hook_resid_post       39    100      0.39

In [11]:
fig = px.line(df_1, x="layer", y="accuracy", title="Accuracy v/s Layer with 100 generations (greedy) ablating 20 SVs")
fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")
fig.show()

In [8]:
df_2 = pd.read_csv('layer_ablation_results_3.csv')
df_2.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       44    100      0.44
1      1  blocks.1.hook_resid_post       53    100      0.53
2      2  blocks.2.hook_resid_post       54    100      0.54
3      3  blocks.3.hook_resid_post       50    100      0.50
4      4  blocks.4.hook_resid_post       51    100      0.51

In [10]:
import plotly.express as px

fig = px.line(df_2, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (greedy) STEERING 20 SVs")

fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.show()

In [13]:
df_3 = pd.read_csv('layer_ablation_results_4.csv')
df_3.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       38    100      0.38
1      1  blocks.1.hook_resid_post       16    100      0.16
2      2  blocks.2.hook_resid_post        7    100      0.07
3      3  blocks.3.hook_resid_post        9    100      0.09
4      4  blocks.4.hook_resid_post        9    100      0.09

In [16]:
import plotly.express as px

fig = px.line(df_3, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (greedy) ABLATING 100 SVs")

fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.show()