In [1]:
import numpy as np
import plotly.express as px
import pandas as pd

In [2]:
df = pd.read_csv('layer_ablation_results_triviaqa_10sv.csv')
df.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       52    100      0.52
1      1  blocks.1.hook_resid_post       44    100      0.44
2      2  blocks.2.hook_resid_post       52    100      0.52
3      3  blocks.3.hook_resid_post       45    100      0.45
4      4  blocks.4.hook_resid_post       47    100      0.47

In [3]:
fig = px.line(df, x="layer", y="accuracy", title="Accuracy v/s Layer with 100 generations (greedy) ablating 10 SVs")
fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")
fig.show()

In [4]:
df_1 = pd.read_csv('layer_ablation_results_2.csv')
df_1.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       43    100      0.43
1      1  blocks.1.hook_resid_post       28    100      0.28
2      2  blocks.2.hook_resid_post       37    100      0.37
3      3  blocks.3.hook_resid_post       47    100      0.47
4      4  blocks.4.hook_resid_post       39    100      0.39

In [5]:
fig = px.line(df_1, x="layer", y="accuracy", title="Accuracy v/s Layer with 100 generations (greedy) ablating 20 SVs")
fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")
fig.show()

In [6]:
df_2 = pd.read_csv('layer_ablation_results_3.csv')
df_2.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       44    100      0.44
1      1  blocks.1.hook_resid_post       53    100      0.53
2      2  blocks.2.hook_resid_post       54    100      0.54
3      3  blocks.3.hook_resid_post       50    100      0.50
4      4  blocks.4.hook_resid_post       51    100      0.51

In [7]:
import plotly.express as px

fig = px.line(df_2, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (greedy) STEERING 20 SVs")

fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.show()

In [8]:
df_3 = pd.read_csv('layer_ablation_results_4.csv')
df_3.head()

   layer                 hook_name  correct  total  accuracy
0      0  blocks.0.hook_resid_post       38    100      0.38
1      1  blocks.1.hook_resid_post       16    100      0.16
2      2  blocks.2.hook_resid_post        7    100      0.07
3      3  blocks.3.hook_resid_post        9    100      0.09
4      4  blocks.4.hook_resid_post        9    100      0.09

In [9]:
import plotly.express as px

fig = px.line(df_3, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (greedy) ABLATING 100 SVs")

fig.add_hline(y=0.52, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.show()

In [10]:
df_4 = pd.read_csv('layer_ablation_results_5.csv')

In [12]:
import plotly.express as px

fig = px.line(df_4, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (temperature = 0.7) ABLATING 20 SVs")

fig.add_hline(y=0.50, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.show()

In [17]:
import plotly.express as px
import plotly.graph_objects as go

# First trace from df_4
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_4["layer"],
    y=df_4["accuracy"],
    mode="lines",
    name="20 Singular Vectors with Temperature = 0.7"   # legend label
))

fig.update_layout(
    title="Accuracy v/s Layer (100 generations on TriviaQA with layerwise ablation)",
    showlegend=True
)

# fig.show()

# rename the single trace for the legend
# Add a horizontal baseline
fig.add_hline(
    y=0.50,
    line_dash="dash",
    line_color="red",
    annotation_text="Baseline Accuracy",
    annotation_position="top right"
)

# Add additional dataframes as new traces
fig.add_trace(go.Scatter(
    x=df_3["layer"],
    y=df_3["accuracy"],
    mode="lines",
    name="100 singular vectors with greedy decoding"
))
fig.add_trace(go.Scatter(
    x=df_1["layer"],
    y=df_1["accuracy"],
    mode="lines",
    name="20 singular vectors with greedy decoding"
))

fig.add_trace(go.Scatter(
    x=df["layer"],
    y=df["accuracy"],
    mode="lines",
    name="10 singular vectors with greedy decoding"
))

fig.show()

In [22]:
df_6 = pd.read_csv('layer_ablation_results._random_baselinecsv.csv')
import plotly.express as px

fig = px.line(df_6, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (temperature = 0.7) ABLATING 20 RANDOM SVs")

fig.add_hline(y=0.48, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.update_yaxes(range=[0, 1])

fig.show()

In [25]:
df_7 = pd.read_csv('layer_ablation_results_50_SV.csv')

import plotly.express as px

fig = px.line(df_7, x="layer", y="accuracy",
              title="Accuracy v/s Layer with 100 generations (temperature = 0.7) ABLATING 50 SVs")

fig.add_hline(y=0.50, line_dash="dash", line_color="red",
              annotation_text="Baseline Accuracy", annotation_position="bottom right")

fig.update_yaxes(range=[0, 1])

fig.show()

In [39]:
import textstat

text = "The islets of Langerhans are a group of endocrine cells that produce hormones that act on various target tissues, affecting multiple organs. \n\nHere's a breakdown:\n\n1. **The hormones produced in the islets of Langerhans:**\n    *"
score = textstat.flesch_reading_ease(text)
# ~60–70 = easily readable, higher = simpler

In [40]:
print(score)

60.966960784313756

In [46]:
import json
import pandas as pd
import plotly.express as px
import textstat

# --- Load JSON ---
with open("layer_ablation_detailed_results_random_baseline.json", "r") as f:
    raw = json.load(f)

rows = []

# --- Iterate over layers ---
for layer_key, entries in raw.items():
    layer_num = int(layer_key)      # keys are "0", "1", ...
    scores = []
    for item in entries:
        text = item.get("generated_answer", "")
        # Compute Flesch Reading Ease (higher = easier to read)
        scores.append(textstat.flesch_reading_ease(text))
    if scores:  # avoid empty layer
        rows.append({"layer": layer_num, "avg_score": sum(scores) / len(scores)})

df = pd.DataFrame(rows).sort_values("layer")

# --- Plot ---
fig = px.line(
    df,
    x="layer",
    y="avg_score",
    markers=True,
    title="Average Flesch Reading Ease vs Layer"
)
fig.update_yaxes(title="Average Reading Ease (0–100 scale)")
fig.update_xaxes(title="Layer", dtick=1)
fig.update_yaxes(range=[0, 100])
fig.show()

In [54]:
import torch
import re
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer("all-mpnet-base-v2")

def coherence_score(sentence):
    parts = [c.strip() for c in re.split(r'[.;:!?]', sentence) if c.strip()]
    if len(parts) < 2: return 1.0
    embeds = model.encode(parts, convert_to_tensor=True)
    sims = [util.cos_sim(embeds[i], embeds[i+1]) for i in range(len(embeds)-1)]
    return float(torch.stack(sims).mean())

In [57]:
import re
print(coherence_score('**Tribal groups** \n\n\nLet me know if youd like to learn more about these or other Native American tribes!'))

1.0